//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAplication.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string accountnum { get; set; }
        public Nullable<decimal> codclient { get; set; }
        public Nullable<decimal> coddept { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string correlative { get; set; }
        public Nullable<bool> states { get; set; }
        public Nullable<decimal> coin { get; set; }
    }
}
