//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAplication.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COIN
    {
        public decimal idcoin { get; set; }
        public string codcoin { get; set; }
        public string type { get; set; }
        public string codmov { get; set; }
    }
}
