//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAplication.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENT
    {
        public decimal iddept { get; set; }
        public string coddept { get; set; }
        public string description { get; set; }
    }
}
