//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAplication.ModelEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbbankaplicationEntitiesBanck : DbContext
    {
        public dbbankaplicationEntitiesBanck()
            : base("name=dbbankaplicationEntitiesBanck")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<COIN> COINs { get; set; }
        public virtual DbSet<DEPARTAMENT> DEPARTAMENTs { get; set; }
        public virtual DbSet<MOVEMENT> MOVEMENTs { get; set; }
    }
}
