//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAplication.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVEMENT
    {
        public decimal idmov { get; set; }
        public string accountnum { get; set; }
        public Nullable<decimal> codcoin { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string type { get; set; }
    }
}
